# -*- coding: future_fstrings -*-

from typing import Any, Dict, List, Optional, NewType, TypeVar
from dataclasses import dataclass

@dataclass
class AuthSet:
    """
    Authentication data set ID.
    """
    id: Optional[str] = None
    """
    The device&#39;s public key, generated by the device or pre-provisioned by the vendor.
    """
    pubkey: Optional[str] = None
    """
    
    """
    identity_data: Optional[IdentityData] = None
    """
    
    """
    status: Optional[str] = None
    """
    Created timestamp
    """
    ts: Optional[str] = None

