# -*- coding: future_fstrings -*-

from typing import Any, Dict, List, Optional, NewType, TypeVar
from dataclasses import dataclass

@dataclass
class PreAuthSet:
    identity_data: IdentityData
    """
    
    """
    pubkey: str
    """
    The device&#39;s public key, generated by the device or pre-provisioned by the vendor.
    """

